-- MySQL Script generated by MySQL Workbench
-- Tue Nov 10 05:12:16 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema marketplace
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema marketplace
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `marketplace` DEFAULT CHARACTER SET utf8 ;
USE `marketplace` ;

-- -----------------------------------------------------
-- Table `marketplace`.`sellers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `marketplace`.`sellers` (
  `seller_id` INT(10) NOT NULL AUTO_INCREMENT,
  `seller_name` VARCHAR(255) NULL,
  `seller_adress` VARCHAR(255) NULL,
  `seller_email` VARCHAR(255) NULL,
  PRIMARY KEY (`seller_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `marketplace`.`brands`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `marketplace`.`brands` (
  `brand_id` INT(10) NOT NULL AUTO_INCREMENT,
  `brand_name` VARCHAR(255) NULL,
  `brand_slogan` VARCHAR(255) NULL,
  `brand_logo` BLOB NULL,
  `brand_description` TEXT NULL,
  PRIMARY KEY (`brand_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `marketplace`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `marketplace`.`products` (
  `product_id` INT(13) NOT NULL AUTO_INCREMENT,
  `product_name` VARCHAR(100) NULL,
  `product_shortDescription` VARCHAR(255) NULL,
  `product_longDescription` TEXT NULL,
  `product_priceHT` FLOAT(8) NULL,
  `product_deliveryHT` FLOAT(6) NULL,
  `brand_id` INT(10) NOT NULL,
  PRIMARY KEY (`product_id`),
  CONSTRAINT `fk_products_brands1`
    FOREIGN KEY (`brands_brand_id`)
    REFERENCES `marketplace`.`brands` (`brand_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `marketplace`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `marketplace`.`categories` (
  `category_id` INT(10) NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(255) NULL,
  `category_description` TEXT NULL,
  PRIMARY KEY (`category_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `marketplace`.`products_sellers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `marketplace`.`products_sellers` (
  `selller_id` INT NOT NULL,
  `product_id` INT(13) NOT NULL,
  `product_stock` VARCHAR(45) NULL,
  PRIMARY KEY (`selller_id`, `product_id`),
  CONSTRAINT `fk_sellers_has_products_sellers`
    FOREIGN KEY (`selller_id`)
    REFERENCES `marketplace`.`sellers` (`seller_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sellers_has_products_products1`
    FOREIGN KEY (`product_id`)
    REFERENCES `marketplace`.`products` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;




-- -----------------------------------------------------
-- Table `marketplace`.`categories_products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `marketplace`.`categories_products` (
  `category_id` INT(10) NOT NULL,
  `product_id` INT(13) NOT NULL,
  PRIMARY KEY (`category_id`, `product_id`),
  CONSTRAINT `fk_categories_has_products_categories1`
    FOREIGN KEY (`category_id`)
    REFERENCES `marketplace`.`categories` (`category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_categories_has_products_products1`
    FOREIGN KEY (`product_id`)
    REFERENCES `marketplace`.`products` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
